version: '3.8'
services:
  mysql:
    image: mysql:8
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: librarydb
    ports:
      - "3307:3306"
    networks:
      - mynetwork

  app:
    image: library_management_system
    container_name: library_app
    ports:
      - "8095:8095"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/librarydb
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
    depends_on:
      - mysql
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge
